# 基础镜像
FROM node:16.14.2-alpine

# 设置工作目录 将根目录下的文件都copy到container（运行此镜像的容器）文件系统的app文件夹下
ADD . /app
# cd到/app/asurada_management/server文件夹下
WORKDIR /app/asurada_management/server

#package.json 没有修改不重新安装依赖
COPY package.json .

# 对外暴露的端口号
EXPOSE 3001

RUN npm install --registry=https://registry.npm.taobao.org



CMD npm run dev